metadata:
  labels:
    project: ${project.artifactId}
    hystrix.enabled: true
    label.hystrix.cluster: default
    version: ${project.version}
spec:
  replicas: 1
  template:
    spec:
      serviceAccount: ribbon